name: CI Build all products

on:
  workflow_call:
  workflow_dispatch:

permissions:
  packages: read

jobs:
  build_all:
    strategy:
      matrix:
        builds:
          - [ FiveM,  five,   x64 ]
          - [ RedM,   rdr3,   x64 ]
          - [ Server, server, x64 ]
    name: ${{ matrix.builds[0] }}
    runs-on: windows-latest
    env:
      PROGRAM: ${{ matrix.builds[1] }}
      PLATFORM: ${{ matrix.builds[2] }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Prepare build folders and env
        shell: pwsh
        run: |
          $root = "C:\b"
          $env:ROOT = $root
          $env:ROOT_REPO = "$root\$env:PROGRAM"
          $env:ROOT_DEP = "$root\dep"
          $env:JOB_SLOTS = 2
          echo "ROOT_REPO=$($env:ROOT_REPO)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ROOT_DEP=$($env:ROOT_DEP)" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "JOB_SLOTS=$($env:JOB_SLOTS)" | Out-File -FilePath $env:GITHUB_ENV -Append
          New-Item -ItemType Directory -Force -Path $env:ROOT_REPO | Out-Null
          New-Item -ItemType Directory -Force -Path $env:ROOT_DEP | Out-Null
          Copy-Item -Recurse -Force "$env:GITHUB_WORKSPACE\*" $env:ROOT_REPO

      - name: Compile
        shell: pwsh
        run: |
          cd $env:ROOT_REPO
          $buildScript = ".github/workflows/ci/build_windows.sh"
          if (!(Test-Path $buildScript)) {
            Write-Error "$buildScript not found!"
            exit 1
          }
          # 传递 x64 给 build_windows.sh
          bash $buildScript "$env:ROOT_DEP" $env:JOB_SLOTS $env:PLATFORM
